### ISSUE TITLE
maser error when creating maser object

### ISSUE THREAD

**Issue by jbubenik** [DiogoVeiga/maser#12]
Hi Diogo, 
It seems that the column names in rMATS4 output files are not the same as is the example file ( IJC vs IC and SJC vs SC).  This is causing the following error : Error in '[.data.frame'(events, , counts.col[1]) : undefined columns selected.  When I change the name of my columns to match the example file everything is fine.  It would be great if you could change the code to accept the IJC and SJC labels as well.  Thanks

Jodi

**Comment by DiogoVeiga** [comment]
Hi Jodi,

Thanks, I will fix the code for reading rMATS4 input files.

**Comment by DiogoVeiga** [comment]
Hi @jbubenik ,

I released a new version on Github to fix this problem.
To create a maser object from rMATS versions >4.0.1,  set the ftype argument to "JCEC" or "JC".

devtools::install_github("DiogoVeiga/maser")
maser(path, c("cond.A", "cond.B"), ftype = "JCEC")
