### ISSUE TITLE
saving plot as .svg

### ISSUE THREAD

**Issue by arphatak** [DiogoVeiga/maser#13]
Hello - I have errors saving the plots generated by maser in .svg format. RStudio plots crash and all the plots need to be re-made. Not sure if I am doing something wrong or if its a bug! Also, this is a very useful package!!

Many thanks!

**Comment by DiogoVeiga** [comment]
Hi, thanks for using the package. Saving in SVG is working fine on my RStudio (version 1.1.4, Mac ).  Is it happening with other R plots as well? Maybe you could try to update your RStudio or try other file extensions like PDF.

**Comment by arphatak** [comment]
Thank you! I am using RStudio on Mac. You are right. This seems to be an issue for other packages as well. I am using RStudio version 1.1.456 on Mac - will try to fix this. Thanks again!
