### ISSUE TITLE
Error in .Call2 

### ISSUE THREAD

**Issue by AhmadReza2** [DiogoVeiga/maser#15]
Hi,

I'm using rMATS v4.0.1 (turbo) for alternative splicing analysis. I want to visualize the output by maser 0.99.16 but encountered the following error.

Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") :

  solving row 4462: range cannot be determined from the supplied arguments (too many NAs)

In addition: Warning messages:

1: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :

  EOF within quoted string

2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :

  number of items read is not a multiple of the number of columns
 

Can you suggest me how to fix this error?

Thanks

**Comment by DiogoVeiga** [comment]
Hi @AhmadReza2 ,

could you send more details. Do you get the error when importing the files or another function?

**Comment by AhmadReza2** [comment]
Hi Diogo,
I get the error when running **maser** function.
`mydata <- maser(path, c("C", "T"), ftype = "JCEC")`
The sample data is attached.
[MXE.MATS.JCEC.txt](https://github.com/DiogoVeiga/maser/files/2369339/MXE.MATS.JCEC.txt)

Thanks

**Comment by AhmadReza2** [comment]
> Hi @AhmadReza2 ,
> 
> could you send more details. Do you get the error when importing the files or another function?

**Comment by AhmadReza2** [comment]
> Hi @AhmadReza2 ,
> 
> could you send more details. Do you get the error when importing the files or another function?
Hi Diogo,
I get the error when running maser function.
mydata <- maser(path, c("C", "T"), ftype = "JCEC")
The sample data is attached.

[MXE.MATS.JCEC.txt](https://github.com/DiogoVeiga/maser/files/2386455/MXE.MATS.JCEC.txt)

Thanks
