### ISSUE TITLE
axes labels in volcano()

### ISSUE THREAD

**Issue by colin986** [DiogoVeiga/maser#17]
Hi Diogo, 

The axes labels in volcano() are incorrect - the X should be delta PSI and Y log10 adj.Pvalue.

Regards,
C

**Comment by ssayols** [comment]
Hi Colin,
This repo seems to be rather quiet...
For who arrives here with the same issue: the volcano is just a ggplot object, and therefore you can overwrite the labels with:

```R
volcano(hypoxia_filt, type="SE") + 
     labs(y="Log10 Adj. Pvalue", x="Delta PSI")   # <-- this will overwrite the wrongly placed labels
```

As a side note: as of Jan 2021 the package crashes at building in Bioconductor, so it may be a matter of time until the package is eventually removed if the issues are not addressed.

**Comment by DiogoVeiga** [comment]
Thank for you your comment, the issue has now been solved in the new version.
