### ISSUE TITLE
geneEvents() not compatible with mm10 Ensembl | gencode builds ?

### ISSUE THREAD

**Issue by seyfim** [DiogoVeiga/maser#21]
@DiogoVeiga I am user maser with mm10 rMATS 4.0.2 output and am getting the following:
`wtmut<-maser(rawdeltadirs, c("Wt", "Mut"), ftype ="JCEC")`
`ens_gtf<-rtracklayer::import.gff(GTF)`
`gene_events<-geneEvents(wtmut, geneS='Bcap31')`
`plotTranscripts(gene_events, type="SE", event_id=0, gtf=ens_gtf)`
`Error in `[[<-`(`*tmp*`, name, value = c("Inclusion", "Inclusion", "Inclusion",  :` 
 ` 5 elements in value to replace 0 elements`
`sessionInfo()`
`R version 3.6.1 (2019-07-05)'
'Platform: x86_64-apple-darwin15.6.0 (64-bit)'
'Running under: macOS Mojave 10.14.6`

To trouble-shoot I have tried:

- removed and reinstalled the maser package 

- gencode aligned bams->rMATs4.0.2  pipeline with the most current mm10 gencode gtf (gencode.vM23.annotation.gtf)

- Ensembl aligned bams->rMATs4.0.2  pipeline with the most current mm10 Ensembl gtf (Mus_musculus.GRCm38.98.gtf)

**any advice is GREATLY appreciated!!**

**Comment by DiogoVeiga** [comment]
The package currently only supports the mapping of events to human hg38 GTFs.
