### ISSUE TITLE
geneEvents with GeneID?

### ISSUE THREAD

**Issue by preetomregon** [DiogoVeiga/maser#23]
I am having an issue getting the Gene-specific events with **geneEvents** and plotting. As per the manual, it can be retrieved by **geneS** which takes the character of **geneSymbol** column. In my GTF file, there is no gene symbol or description. The same happened with my rMATS output.  Can I get the Gene-specific events with **GeneID** or **event_id**? I tried but nothing comes. Please suggest.. 
Thanks.
 
`path <- system.file("extdata", file.path("rmats_output"), package = "maser")`
`as_event <- maser(path, c("control", "treated"), ftype = "JCEC")`
`as_event`
> A Maser object with 12813 splicing events.
Samples description: 
Label=control     n=3 replicates
Label=treated     n=3 replicates
Splicing events: 
A3SS.......... 1550 events
A5SS.......... 797 events
SE.......... 8421 events
RI.......... 1453 events
MXE.......... 592 events

`head(summary(as_event))`
![maser1](https://user-images.githubusercontent.com/39555654/81467525-c3bac100-91f6-11ea-894b-57c9b7e9a7e3.JPG)
`as_event_filt <- filterByCoverage(as_event, avg_reads = 5)`
`as_event_filt`

> A Maser object with 10096 splicing events.
Samples description: 
Label=control     n=3 replicates
Label=treated     n=3 replicates
Splicing events: 
A3SS.......... 1014 events
A5SS.......... 478 events
SE.......... 7767 events
RI.......... 303 events
MXE.......... 534 events

The rMATS output and GTF files are in the attached folder.
[MXE.MATS.JCEC.zip](https://github.com/DiogoVeiga/maser/files/4602955/MXE.MATS.JCEC.zip)

**Comment by DiogoVeiga** [comment]
Hi,

the package was designed to work with an Ensembl/GENCODE hg38 GTF  containing the geneSymbol annotation. As a workaround, you could modify your GTF and rMATS files before downstream analyses with the package.

**Comment by MPriebe** [comment]
Hi there I am having a similar problem with the package, my rmats output has no genesymbols but only geneIDs. I have tried the suggested workaround by replacing the NAs in the genesymbol column with the geneID from the previous column in all the relevant text files using an awk command:
```
for file in maser_input/*.MATS.*.txt maser_input/from*.txt; do
	identifier=$(basename "$file")
	echo "Writing genesymbols for file ${identifier}"
		awk '{if (NR!=1){$3 = $2;print} else {print}}' rmats_results/${identifier} > maser_input/${identifier}
		
done
```

when I try and run maser on this new input directory I get the following error:
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 23 elements

Is there any workaround that can be done within R to adjust the maser object by any chance? Any help with this would be greatly appreciated!

**Comment by DiogoVeiga** [comment]
I suggest adding this information to your GTF if you are using a custom GTF that does not follow Gencode/Ensembl standard. You will probably be able to add the gene symbol information and export the new GTF using the export function of the  rtracklayer package. Perhaps this post can help
[https://support.bioconductor.org/p/93917/](url)
