### ISSUE TITLE
mapTranscriptsToEvents fails

### ISSUE THREAD

**Issue by rscmauer** [DiogoVeiga/maser#28]
Hi,

I'm getting the following error when using mapTranscriptsToEvents:
1: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr19, chr7, chr20, chr4, chr10, chr16, chr22, chr2, chr12, chr5, chr21, chrX, chr6, chr8, chr1, chr9, chr18, chr17, chr3, chr15, chr14, chr11, chr13, chrY
  - in 'y': chrchr1, chrchr2, chrchr3, chrchr4, chrchr5, chrchr6, chrchr7, chrchr8, chrchr9, chrchr10, chrchr11, chrchr12, chrchr13, chrchr14, chrchr15, chrchr16, chrchr17, chrchr18, chrchr19, chrchr20, chrchr21, chrchr22, chrchrX, chrchrY, chrchrM, chrGL000192.1, chrGL000193.1, chrGL000199.1, chrGL000202.1, chrGL000204.1, chrGL000228.1, chrGL000237.1
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).

It seems that mapTranscriptsToEvents adds chr to all chromosome names of the gtf and I'm not sure why this happens.
This happens with all events in the rMATS output.
I used the same gtf (https://www.gencodegenes.org/human/release_31lift37.html) for mapTranscriptsToEvents and rMATS, so I don't see what the cause for this is.

I would appreciate any feedback on this.

Thanks, Jan

**Comment by DiogoVeiga** [comment]
Hi, can you please use the GTF downloaded from Ensembl?  The package assumes the Ensembl default (no "chr") in transcript/exon definitions. 

http://www.ensembl.org/info/data/ftp/index.html

**Comment by rscmauer** [comment]
Hi Diogo, 
Thanks for the reply.

I will have to rerun the whole rMATS analysis then with the ensembl gtf, correct?

Alternatively, is there any quick fix to allow maser to accept other gtfs e.g. remove the line where chr is added to the chromosome names?

Best, Jan

**Comment by DiogoVeiga** [comment]
Hi Jan,

you don't need to rerun rMATS. Just download GTF directly from Ensembl without the "chr" prefix for the maser analysis and it should work.

Alternatively, you can modify the GTF file you already have with something below.
`sed 's/chr//g' gencode.gtf > new.gencode.gtf`

**Comment by rscmauer** [comment]
Hi Diogo,

sorry for the late reply.
Thanks for the advice, removing the chr string via sed worked like a charm.

Best, Jan
